/* Online runs on Supabase: publishing an experiment for participants,
   recording sessions and trials, and fetching results. A thin REST client
   (PostgREST + GoTrue) with fetch injected, so it is testable offline.
   Schema and policies: server/supabase/schema.sql. */

export const ONLINE_KEY="stimulus-builder.online";   // {url, anonKey}
export const AUTH_KEY="stimulus-builder.auth";       // {access_token, refresh_token, expires_at, email}

const ALPHABET="abcdefghjkmnpqrstuvwxyz23456789";
export function newSlug(n=8,rng=Math.random){let s="";for(let i=0;i<n;i++)s+=ALPHABET[Math.floor(rng()*ALPHABET.length)];return s;}
/* The participant link is self-contained: the published id plus the project
   the data lives in (the anon key is the public client key; row-level
   security is what protects the data). A plain supabase.co project is
   carried as its ref, anything else as the full URL. */
export function projectRef(url){const m=String(url||"").match(/^https:\/\/([a-z0-9-]+)\.supabase\.co\/?$/i);return m?m[1]:String(url||"");}
export function projectUrl(sb){return /^[a-z0-9-]+$/i.test(sb)?`https://${sb}.supabase.co`:String(sb||"");}
export function participantLink(baseHref,id,project=null){
  const u=new URL(baseHref);u.search="";u.hash="";
  const q=new URLSearchParams({run:id});
  if(project&&project.url){q.set("sb",projectRef(project.url));q.set("key",project.anonKey||"");}
  return `${u.href}?${q.toString()}`;
}
/* Prolific appends these to the study URL: ?PROLIFIC_PID={{%PROLIFIC_PID%}}&STUDY_ID={{%STUDY_ID%}}&SESSION_ID={{%SESSION_ID%}} */
export function prolificParams(search){
  const p=new URLSearchParams(search);
  return {run:p.get("run")||"",sb:p.get("sb")||"",key:p.get("key")||"",
          prolific_pid:p.get("PROLIFIC_PID")||"",study_id:p.get("STUDY_ID")||"",session_id:p.get("SESSION_ID")||"",participant:p.get("participant")||""};
}
export function completionTarget(def){
  if(def.completionUrl)return def.completionUrl;
  if(def.completionCode)return `https://app.prolific.com/submissions/complete?cc=${encodeURIComponent(def.completionCode)}`;
  return "";
}
/* flatten fetched sessions (with embedded trials) into result rows */
export function sessionsToRows(sessions){
  const rows=[];
  (sessions||[]).forEach(s=>{
    const trials=[...(s.trials||[])].sort((a,b)=>a.trial-b.trial);
    trials.forEach(t=>rows.push({...t.row,session_id:s.id,session_started:s.created_at,session_completed:s.completed?1:0,
      prolific_pid:s.participant?.prolific_pid||"",study_id:s.participant?.study_id||"",prolific_session_id:s.participant?.session_id||""}));
  });
  return rows;
}
export const SESSION_COLUMNS=["session_id","session_started","session_completed","prolific_pid","study_id","prolific_session_id"];

export class OnlineError extends Error{constructor(msg,status,body){super(msg);this.status=status;this.body=body;}}

export function makeClient({url,anonKey,fetch=globalThis.fetch,getToken=()=>null}){
  const base=String(url||"").replace(/\/+$/,"");
  async function call(path,{method="GET",body,headers={},auth=true}={}){
    const h={"apikey":anonKey,"Content-Type":"application/json",...headers};
    const token=auth?getToken():null;
    h["Authorization"]=`Bearer ${token||anonKey}`;
    const r=await fetch(base+path,{method,headers:h,body:body!==undefined?JSON.stringify(body):undefined});
    const text=await r.text();
    let data=null;try{data=text?JSON.parse(text):null;}catch{data=text;}
    if(!r.ok){
      const msg=(data&&(data.msg||data.message||data.error_description||data.error||data.hint))||`${r.status} ${r.statusText||""}`.trim();
      throw new OnlineError(msg,r.status,data);
    }
    return data;
  }
  return {
    base,
    /* ---- experimenter auth (email + password) ---- */
    signIn:(email,password)=>call("/auth/v1/token?grant_type=password",{method:"POST",body:{email,password},auth:false}),
    refresh:(refresh_token)=>call("/auth/v1/token?grant_type=refresh_token",{method:"POST",body:{refresh_token},auth:false}),
    /* ---- publishing ---- */
    publish:(rec)=>call("/rest/v1/published_experiments",{method:"POST",body:rec,headers:{Prefer:"return=representation"}}).then(r=>Array.isArray(r)?r[0]:r),
    listPublished:()=>call("/rest/v1/published_experiments?select=id,name,canvas,created_at,active,experiment_code&order=created_at.desc"),
    setActive:(id,active)=>call(`/rest/v1/published_experiments?id=eq.${encodeURIComponent(id)}`,{method:"PATCH",body:{active},headers:{Prefer:"return=minimal"}}),
    /* ---- participants (anon) ---- */
    fetchDefinition:async id=>{
      const r=await call(`/rest/v1/published_experiments?id=eq.${encodeURIComponent(id)}&select=id,definition,active&limit=1`,{auth:false});
      return Array.isArray(r)&&r[0]?r[0]:null;
    },
    /* the id is generated by the caller: participants may insert but never read sessions, so nothing can be returned */
    createSession:(rec)=>call("/rest/v1/sessions",{method:"POST",body:rec,headers:{Prefer:"return=minimal"},auth:false}).then(()=>rec),
    postTrial:(session_id,trial,row)=>call("/rest/v1/trials",{method:"POST",body:{session_id,trial,row},headers:{Prefer:"return=minimal"},auth:false}),
    completeSession:(sid)=>call("/rest/v1/rpc/complete_session",{method:"POST",body:{sid},auth:false}),
    /* ---- results (experimenter) ---- */
    fetchSessions:(experiment_id)=>call(`/rest/v1/sessions?experiment_id=eq.${encodeURIComponent(experiment_id)}&select=id,created_at,participant,calibration,completed,completed_at,trials(trial,row)&order=created_at.asc`),
  };
}
